apiVersion: apps/v1
kind: Deployment
metadata:
 name: capstone
spec:
 replicas: 3
 selector:
  matchLabels:
   app: capstone
 template:
  metadata:
   labels:
    app: capstone
  spec:
  containers:
   name: c1
   image: sonal04/capstoneimage
